//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSteelworksMES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int ResourceId { get; set; }
        public System.DateTime Date { get; set; }
        public int EmployeeId { get; set; }
        public int Quantity { get; set; }
        public string SellerName { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
